Jesse
myecentials/ecentials-backend pull request #4
Opened 2022-11-18 14:51 UTC by myecentials

2022-11-19 21:54 UTC, lateofrederick requested changes
Please revise the changes and let me know if you do not get anything

2022-11-19 21:54 UTC, lateofrederick commented on routes/v1/User/orders.js
> +router.post('/create-order-item', verify, async (req, res) => {
everything seems pretty great but I think it would do us good if we extracted the logic into its own service file, also instead of destructing like that you can pass the req object into the service function that would be use in the controller. for inspiration look at the cancelUserAppointments in the appointments.service.js service in the Appointments folder

2022-11-19 21:54 UTC, lateofrederick commented on private/services/User/Orders/orders.service.js
> +
so the mongo db access for creating an order can be extracted as a service here. In actual fact, it should be in a repository folder... but since we did not go that way we should extract it here so that the controllers wont have a lot of logic in it.

2022-11-19 21:55 UTC, lateofrederick commented on routes/v1/User/orders.js
> +router.post('/create-order-item', verify, async (req, res) => {
and let's remove the .clone from the method, it is not performant

2022-11-23 10:33 UTC, myecentials commented on routes/v1/User/orders.js
> +router.post('/create-order-item', verify, async (req, res) => {
i didnt add the clone. You did. 
Anyway, i have removed it.

2022-11-23 10:34 UTC, myecentials commented on private/services/User/Orders/orders.service.js
> +
i tried to understand what you were saying but it still didnt make sense. Can you do this one the way you are describing so i can use it to do the others?

2022-11-24 11:12 UTC, merged